---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: loghouse
  namespace: kube-logging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: ch.domain
    http:
      paths:
      - path: /
        backend:
          serviceName: loghouse
          servicePort: 9292
  tls:
  - hosts:
    - ch.domain
    secretName: loghouse
