---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse
  namespace: kube-logging
  annotations:
    volume.beta.kubernetes.io/mount-options: "discard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ##STORAGE_SIZE##
  storageClassName: ##STORAGE_CLASS_NAME##
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: clickhouse-server
  namespace: kube-logging
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: clickhouse
    spec:
      initContainers:
      - name: chown
        image: alpine:3.6
        command: ['/bin/sh', '-c', 'chown 105:106 -R /var/lib/clickhouse']
        volumeMounts:
          - name: clickhouse
            mountPath: /var/lib/clickhouse
      containers:
      - name: clickhouse
        image:  navyzet/clickhouse:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8123
        - name: native
          containerPort: 9000
        env:
        - name: CLICKHOUSE_SERVER
          value: "clickhouse"
        - name: CLICKHOUSE_PORT
          value: "9000"
        - name: CLICKHOUSE_USER
          value: "default"
        - name: CLICKHOUSE_PASS
          value: "##CLICKHOUSE_PASS##"
        - name: CLICKHOUSE_DB
          value: "##CLICKHOUSE_DB##"
        - name: K8S_LOGS_TABLE
          value: "##K8S_LOGS_TABLE##"
        livenessProbe:
          timeoutSeconds: 1
          initialDelaySeconds: 60
          tcpSocket:
            port: 8123
        readinessProbe:
          timeoutSeconds: 1
          initialDelaySeconds: 5
          tcpSocket:
            port: 8123
        resources:
          requests:
            cpu: "1"
          limits:
            cpu: "4"
        volumeMounts:
          - name: clickhouse
            mountPath: /var/lib/clickhouse/
          - name: config-volume
            mountPath: /etc/clickhouse-server
      volumes:
        - name: clickhouse
          persistentVolumeClaim:
            claimName: clickhouse
        - name: config-volume
          configMap:
            name: clickhouse-config
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: kube-logging
spec:
  selector:
    component: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      protocol: TCP
    - name: native
      port: 9000
      targetPort: 9000
      protocol: TCP
