apiVersion: batch/v1
kind: Job
metadata:
  name: init-clickhouse
  namespace: kube-logging
spec:
  activeDeadlineSeconds: 10
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-clickhouse
        image: alpine:3.6
        command: [ "/bin/sh", "-c", "while ! getent ahostsv4 ${CLICKHOUSE_HOST};do sleep 1; echo -n .;done"]
        env:
        - name: CLICKHOUSE_HOST
          value: ##CLICKHOUSE_HOST##
      containers:
        - name: init-clickhouse
          image: flantasidorov/init-clickhouse
          command: [ "/bin/bash", "-l", "-c", "clickhouse-client --host=${CLICKHOUSE_HOST} --port=${CLICKHOUSE_PORT} --user=${CLICKHOUSE_USER} --query='CREATE DATABASE ${CLICKHOUSE_DB};'; clickhouse-client --host=${CLICKHOUSE_HOST} --port=${CLICKHOUSE_PORT} --user=${CLICKHOUSE_USER} --database=${CLICKHOUSE_DB} --query='CREATE TABLE ${K8S_LOG_TABLE} (log String, stream String, namespace String, pod_name String, container_name String, pod_id String, container_id String, host String, timestamp DateTime, type String) ENGINE = Log;'" ]

