---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tabix
  namespace: kube-logging
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: tabix
    spec:
      containers:
      - name: tabix
        image: wimbo/tabix
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          timeoutSeconds: 1
          initialDelaySeconds: 60
          tcpSocket:
            port: 80
        readinessProbe:
          timeoutSeconds: 1
          initialDelaySeconds: 5
          tcpSocket:
            port: 80
        resources:
          requests:
            cpu: "0.2"
          limits:
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: tabix
  namespace: kube-logging
spec:
  selector:
    component: tabix
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tabix
  namespace: kube-logging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: tabix.kube.allabout.me
    http:
      paths:
      - path: /
        backend:
          serviceName: tabix
          servicePort: http
  tls:
  - hosts:
    - tabix.kube.allabout.me
    secretName: tabix
